services:
  mysql:
    image: mysql
    container_name: mysql_${SITE}
    restart: unless-stopped
    tty: true
    user: "${UID}:${GID}"
    ports:
      - ${DATABASE_PORT}:3306
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      SERVICE_TAGS: ${SERVICE_TAGS}
      SERVICE_NAME: ${SERVICE_NAME}
    command: --default-storage-engine=INNODB  
    networks:
      app:

networks:
  app:  

volumes:
  mysql: